version: "3.7"
services:
  postgres:
    image: postgres:12.7
    container_name: diary-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "15444:5432"
    volumes:
      - ./docker-compose/data:/var/lib/postgresql/data
